apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-api
    level: php
    release: {{ .Release.Name }}
  name: php
spec:
  ports:
  - name: php
    port: 9000 
    protocol: TCP
    targetPort: 9000
  selector:
    app: simple-api
    level: php
    release: {{ .Release.Name }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
